name: ExtendedHorizons
version: ${version}
main: me.mapacheee.extendedhorizons.ExtendedHorizonsPlugin
api-version: '1.21'
folia-supported: true
description: ${description}
author: Mapacheee
website: https://github.com/mapacheee/extendedhorizons

libraries:
 - org.xerial:sqlite-jdbc:3.7.2

depend: [packetevents]
softdepend: [LuckPerms, PlaceholderAPI]

commands:
  extendedhorizons:
    description: Main ExtendedHorizons command
    usage: /<command> [subcommand]
    aliases: [eh, horizons, viewdistance, vd]
    permission: extendedhorizons.use

permissions:
  extendedhorizons.use:
    description: Basic permission to use ExtendedHorizons commands
    default: true
  extendedhorizons.distance.16:
    description: Allow view distance up to 16 chunks
    default: true
  extendedhorizons.distance.32:
    description: Allow view distance up to 32 chunks
    default: op
  extendedhorizons.distance.64:
    description: Allow view distance up to 64 chunks
    default: false
  extendedhorizons.distance.unlimited:
    description: Allow unlimited view distance
    default: false
  extendedhorizons.admin:
    description: Access to admin commands
    default: op
  extendedhorizons.bypass.limits:
    description: Bypass network and performance limits
    default: false
