package me.mapacheee.extendedhorizons.viewdistance.service.strategy;

import me.mapacheee.extendedhorizons.viewdistance.service.player.PlayerChunkState;
import org.bukkit.entity.Player;

import java.util.List;
import java.util.Set;

/**
 * Defines the strategy for prioritizing and queueing fake chunks for players.
 * 
 * Implementations control:
 * 1. Warmup behavior (teleport detection)
 * 2. Chunk prioritization (sorting)
 * 3. Queue management (cleansing irrelevant chunks)
 */
public interface ChunkLoadStrategy {

    /**
     * Called on every view update cycle to track player movement and detecting
     * teleports.
     * 
     * @param player The player
     * @param state  The player's chunk state
     */
    void onPlayerUpdate(Player player, PlayerChunkState state);

    /**
     * Checks if special warmup processing is currently active for this player.
     * 
     * @param player The player
     * @param state  The player's chunk state
     * @return true if warmup logic should be applied
     */
    boolean isWarmupActive(Player player, PlayerChunkState state);

    /**
     * Handles processing chunks during a warmup period (e.g., after teleport).
     * Typically involves aggressive sorting of ALL visible chunks and replacing the
     * queue.
     * 
     * @param player           The player
     * @param state            The player's chunk state
     * @param allVisibleChunks All chunks currently within the player's view
     *                         distance
     */
    void processWarmup(Player player, PlayerChunkState state, Set<Long> allVisibleChunks);

    /**
     * Handles standard processing of new chunks during normal movement.
     * Typically involves incremental sorting of ONLY missing chunks and appending
     * to queue.
     * 
     * @param player              The player
     * @param state               The player's chunk state
     * @param newChunksToLoad     Chunks that are visible but not yet sent or
     *                            generated
     * @param globalGeneratingSet The set of chunks currently being generated by the
     *                            system (for cleanup)
     */
    void processQueue(Player player, PlayerChunkState state, List<Long> newChunksToLoad, Set<Long> globalGeneratingSet);
}
